// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMm54IqIsRg41fU8grT3bEVIwTKXc-82M',
    appId: '1:47887870879:web:2418b4d29927da89a6ebaa',
    messagingSenderId: '47887870879',
    projectId: 'fcm-v1-90e68',
    authDomain: 'fcm-v1-90e68.firebaseapp.com',
    storageBucket: 'fcm-v1-90e68.appspot.com',
    measurementId: 'G-BHVYXNY2X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkVjWUrAPz4fNO76Ofn6ukGqIlBVi7Z6M',
    appId: '1:47887870879:android:be8b0a3248f4a6d2a6ebaa',
    messagingSenderId: '47887870879',
    projectId: 'fcm-v1-90e68',
    storageBucket: 'fcm-v1-90e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DL-T3xx-RO7PSkZqMNz--iiQlYMElVs',
    appId: '1:47887870879:ios:aade97a657f4f1d5a6ebaa',
    messagingSenderId: '47887870879',
    projectId: 'fcm-v1-90e68',
    storageBucket: 'fcm-v1-90e68.appspot.com',
    androidClientId: '47887870879-d82r8lbrhomoc5tt1ba1eu9sf60ii817.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmV1Journey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_DL-T3xx-RO7PSkZqMNz--iiQlYMElVs',
    appId: '1:47887870879:ios:aade97a657f4f1d5a6ebaa',
    messagingSenderId: '47887870879',
    projectId: 'fcm-v1-90e68',
    storageBucket: 'fcm-v1-90e68.appspot.com',
    androidClientId: '47887870879-d82r8lbrhomoc5tt1ba1eu9sf60ii817.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmV1Journey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMm54IqIsRg41fU8grT3bEVIwTKXc-82M',
    appId: '1:47887870879:web:dae55d2827dea1aaa6ebaa',
    messagingSenderId: '47887870879',
    projectId: 'fcm-v1-90e68',
    authDomain: 'fcm-v1-90e68.firebaseapp.com',
    storageBucket: 'fcm-v1-90e68.appspot.com',
    measurementId: 'G-MM51QNQQXE',
  );
}
